[workspace]
resolver = "2"
members = ["crates/twrite", "crates/twrite-core", "crates/twrite-gpui"]

[workspace.package]
version = "0.8.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/ToonionOfficial/twrite"
authors = ["Toonion"]

[workspace.dependencies]
ropey = "1.6.1"
regex = "1"
thiserror = "1.0"
unicode-width = "0.2"
pulldown-cmark = { version = "0.12", default-features = false }
gpui = "0.2.2"

twrite = { version = "0.8.0", path = "crates/twrite" }
twrite-core = { version = "0.8.0", path = "crates/twrite-core" }
twrite-gpui = { version = "0.8.0", path = "crates/twrite-gpui" }
