[package]
name = "twrite"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A fast, modular, customizable text editor engine for GPUI"

[dependencies]
twrite-core = { workspace = true }
twrite-gpui = { workspace = true }
gpui = { workspace = true }
gpui_platform = { workspace = true }

[features]
default = []
markdown = ["twrite-core/markdown", "twrite-gpui/markdown"]

[[example]]
name = "simple"
path = "../../examples/simple.rs"

[[example]]
name = "syntax"
path = "../../examples/syntax.rs"

[[example]]
name = "hooks"
path = "../../examples/hooks.rs"

[[example]]
name = "vim"
path = "../../examples/vim.rs"

[[example]]
name = "markdown"
path = "../../examples/markdown.rs"
required-features = ["markdown"]
