[package]
name = "gpui-api-compatibility"
version = "1.0.0"
edition = "2024"

[workspace]

# This example verifies compatibility against latest version of GPUI.
[dependencies]
twrite = { features = ["gpui-zed-1-0"], path = "../../crates/twrite" }
gpui = "0.2.2"
gpui_platform = { git = "https://github.com/zed-industries/zed", version = ">=0.1.0" }

[patch.crates-io]
gpui = { git = "https://github.com/zed-industries/zed", version = ">=0.2.2" }
